name: Deploy

on:
  push:
    branches:
      - "main"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.releases.outputs.releases }}
    steps:
      - id: releases
        run: |
          echo "releases=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/${{github.repository}}/releases?per_page=100" | jq -c '[.[].tag_name]')" >> $GITHUB_OUTPUT
  releases:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release: ${{fromJson(needs.setup.outputs.releases)}}
    steps:
      - uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          version: 'tags/${{ matrix.release }}'
          file: 'constraints-oapi.json'
          target: 'deploy/releases/${{ matrix.release }}/constraints-oapi.json'
      - name: Save releases (artifact)
        uses: actions/upload-artifact@v3
        with:
          name: releases
          retention-days: 7
          path: |
            deploy/releases
  deploy:
    needs: releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm i -g @apidevtools/swagger-cli@4
      - name: Prepare deploy directory
        run: |
          mkdir ./deploy
          cp -r dist ./deploy
          cp -r assets ./deploy
          cp index.html ./deploy
          cp validator-flow.md ./deploy
      - name: Restore releases
        uses: actions/download-artifact@v3
        with:
          name: releases
          path: deploy/releases
      - name: Bundle spec
        run: "swagger-cli bundle ./constraints-oapi.yml -r -t yaml -o ./deploy/constraints-oapi.yml"
      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
